package admin

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"
)

// The activation path has one property worth protecting above all others: it
// must never report a hot-swap that did not happen. Every other detail here is
// in service of that — an operator who trusts a false green tick will read a
// report generated by the previous adapter and attribute it to the new one.

type fakeSwapper struct {
	configured bool
	err        error
	calls      []string
	took       time.Duration
}

func (f *fakeSwapper) Configured() bool { return f.configured }

func (f *fakeSwapper) Activate(_ context.Context, name string) (time.Duration, error) {
	f.calls = append(f.calls, name)
	if f.err != nil {
		return 0, f.err
	}
	return f.took, nil
}

func (f *fakeSwapper) Active(context.Context) (string, error) { return "", nil }

func TestSwapAppliesTheAdapterAndReportsTheDuration(t *testing.T) {
	f := &fakeSwapper{configured: true, took: 12 * time.Millisecond}
	h := &Handler{runtime: f}

	res := h.swap(context.Background(), "tuned-v1.gguf", nil)

	if !res.HotSwapped {
		t.Fatalf("want a hot swap, got note: %s", res.Note)
	}
	if res.SwapMs != 12 {
		t.Errorf("want the measured 12ms reported, got %d", res.SwapMs)
	}
	if len(f.calls) != 1 || f.calls[0] != "tuned-v1.gguf" {
		t.Errorf("want the adapter applied by name, got %v", f.calls)
	}
}

// The likeliest real failure: the file was published but llama-server has not
// been restarted, so it never loaded it. Reporting success here is the specific
// lie this whole test file exists to prevent.
func TestSwapFailureIsNotReportedAsSuccess(t *testing.T) {
	f := &fakeSwapper{configured: true, err: errors.New("adapter is not loaded by the runtime")}
	h := &Handler{runtime: f}

	res := h.swap(context.Background(), "tuned-v1.gguf", nil)

	if res.HotSwapped {
		t.Fatal("a failed swap must not be reported as hot-swapped")
	}
	if res.SwapMs != 0 {
		t.Errorf("a failed swap has no duration, got %d", res.SwapMs)
	}
	if !strings.Contains(res.Note, "not loaded") {
		t.Errorf("the note should carry the runtime's reason, got: %s", res.Note)
	}
	// The compiled path did take effect, and saying otherwise would send the
	// operator looking for a problem that is not there.
	if !strings.Contains(res.Note, "Derlenmiş model değişti") {
		t.Errorf("the note should still confirm what did work, got: %s", res.Note)
	}
}

// Deactivation must reach the engine. A database-only revert leaves the runtime
// applying the adapter that is being rolled back — the worst possible moment
// for the two to disagree.
func TestDeactivationResetsTheRuntime(t *testing.T) {
	f := &fakeSwapper{configured: true}
	h := &Handler{runtime: f}

	res := h.swap(context.Background(), "", nil)

	if len(f.calls) != 1 || f.calls[0] != "" {
		t.Fatalf("want the runtime reset to the base, got calls %v", f.calls)
	}
	if !res.HotSwapped {
		t.Errorf("resetting to the base is still a swap, got note: %s", res.Note)
	}
}

func TestBuildWithoutAGGUFArtefactSaysSo(t *testing.T) {
	// Not configured, so the "" branch must not try to reach a runtime at all.
	h := &Handler{runtime: &fakeSwapper{configured: false}}

	res := h.swap(context.Background(), "", nil)

	if res.HotSwapped {
		t.Fatal("nothing was swapped")
	}
	if !strings.Contains(res.Note, "build_gguf.sh") {
		t.Errorf("the note should say how to make this build swappable, got: %s", res.Note)
	}
}

func TestUnconfiguredRuntimeDoesNotClaimAHotSwap(t *testing.T) {
	f := &fakeSwapper{configured: false}
	h := &Handler{runtime: f}

	res := h.swap(context.Background(), "tuned-v1.gguf", nil)

	if res.HotSwapped {
		t.Fatal("no runtime, no swap")
	}
	if len(f.calls) != 0 {
		t.Errorf("an unconfigured runtime must not be called, got %v", f.calls)
	}
	if !strings.Contains(res.Note, "yapılandırılmamış") {
		t.Errorf("got: %s", res.Note)
	}
}

// A deployment with only the compiled engine passes nil. That is a supported
// configuration, not an error, and it must not panic.
func TestNilRuntimeIsASupportedDeployment(t *testing.T) {
	h := &Handler{runtime: nil}
	if h.hotSwapReady() {
		t.Fatal("a nil runtime is not ready")
	}
	res := h.swap(context.Background(), "tuned-v1.gguf", nil)
	if res.HotSwapped {
		t.Fatal("nothing to swap on")
	}
}
